// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQduqCz8vQ4tMSPZYAxtuzLcjfcVdugeY',
    appId: '1:758765457016:android:d32ff29643bc8da23b278d',
    messagingSenderId: '758765457016',
    projectId: 'aplikasi-note-mplatfor',
    storageBucket: 'aplikasi-note-mplatfor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvT1qb2EGOaCr_pwkhTRUc4sXG3XVy1Q',
    appId: '1:758765457016:ios:fcffd4d7f9be998a3b278d',
    messagingSenderId: '758765457016',
    projectId: 'aplikasi-note-mplatfor',
    storageBucket: 'aplikasi-note-mplatfor.firebasestorage.app',
    iosBundleId: 'com.example.projectNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSvT1qb2EGOaCr_pwkhTRUc4sXG3XVy1Q',
    appId: '1:758765457016:ios:fcffd4d7f9be998a3b278d',
    messagingSenderId: '758765457016',
    projectId: 'aplikasi-note-mplatfor',
    storageBucket: 'aplikasi-note-mplatfor.firebasestorage.app',
    iosBundleId: 'com.example.projectNote',
  );
}
